In [1]:
!pip install datasets
!pip install scikit-learn
!pip install ibm-watson-machine-learning==1.0.312

Requirement already satisfied: datasets in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (2.18.0)
Requirement already satisfied: filelock in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=12.0.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (15.0.1)
Requirement already satisfied: pyarrow-hotfix in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (2.32.2)
Requirement already satisfied: tqdm>=4.62.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (4.66.4)
Requirement already satisfied: xxhash in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec<=2024.2.0,>=2023.1.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from fsspec[http]<=2024.2.0,>=2023.1.0->datasets) (2023.10.0)
Requirement already satisfied: aiohttp in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (3.11.10)
Requirement already satisfied: huggingface-hub>=0.19.4 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (0.29.2)
Requirement already satisfied: packaging in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from datasets) (6.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (0.2.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from aiohttp->datasets) (1.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from huggingface-hub>=0.19.4->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from requests>=2.19.0->datasets) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from requests>=2.19.0->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from requests>=2.19.0->datasets) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from requests>=2.19.0->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: scikit-learn in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from scikit-learn) (2.2.0)
Collecting ibm-watson-machine-learning==1.0.312
  Downloading ibm_watson_machine_learning-1.0.312-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: requests in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (2.32.2)
Requirement already satisfied: urllib3 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (1.26.19)
Collecting pandas<1.6.0,>=0.24.2 (from ibm-watson-machine-learning==1.0.312)
  Downloading pandas-1.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: certifi in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (2025.1.31)
Requirement already satisfied: lomond in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (0.3.3)
Requirement already satisfied: tabulate in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (0.8.10)
Requirement already satisfied: packaging in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (23.2)
Requirement already satisfied: importlib-metadata in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (7.0.1)
Requirement already satisfied: ibm-cos-sdk<2.14.0,>=2.12.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-watson-machine-learning==1.0.312) (2.13.4)
Requirement already satisfied: ibm-cos-sdk-core==2.13.4 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-cos-sdk<2.14.0,>=2.12.0->ibm-watson-machine-learning==1.0.312) (2.13.4)
Requirement already satisfied: ibm-cos-sdk-s3transfer==2.13.4 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-cos-sdk<2.14.0,>=2.12.0->ibm-watson-machine-learning==1.0.312) (2.13.4)
Requirement already satisfied: jmespath<=1.0.1,>=0.10.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-cos-sdk<2.14.0,>=2.12.0->ibm-watson-machine-learning==1.0.312) (1.0.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from ibm-cos-sdk-core==2.13.4->ibm-cos-sdk<2.14.0,>=2.12.0->ibm-watson-machine-learning==1.0.312) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from pandas<1.6.0,>=0.24.2->ibm-watson-machine-learning==1.0.312) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from pandas<1.6.0,>=0.24.2->ibm-watson-machine-learning==1.0.312) (1.26.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from requests->ibm-watson-machine-learning==1.0.312) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from requests->ibm-watson-machine-learning==1.0.312) (3.7)
Requirement already satisfied: zipp>=0.5 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from importlib-metadata->ibm-watson-machine-learning==1.0.312) (3.20.2)
Requirement already satisfied: six>=1.10.0 in /opt/conda/envs/Python-RT24.1/lib/python3.11/site-packages (from lomond->ibm-watson-machine-learning==1.0.312) (1.16.0)
Downloading ibm_watson_machine_learning-1.0.312-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.8 MB/s eta 0:00:00a 0:00:01
Downloading pandas-1.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 76.5 MB/s eta 0:00:00:00:010:01
Installing collected packages: pandas, ibm-watson-machine-learning
  Attempting uninstall: pandas
    Found existing installation: pandas 2.1.4
    Uninstalling pandas-2.1.4:
      Successfully uninstalled pandas-2.1.4
  Attempting uninstall: ibm-watson-machine-learning
    Found existing installation: ibm_watson_machine_learning 1.0.367
    Uninstalling ibm_watson_machine_learning-1.0.367:
      Successfully uninstalled ibm_watson_machine_learning-1.0.367
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autoai-ts-libs 4.0.15 requires pandas==2.1.*, but you have pandas 1.5.3 which is incompatible.
autoai-libs 2.0.11 requires pandas==2.1.*, but you have pandas 1.5.3 which is incompatible.
Successfully installed ibm-watson-machine-learning-1.0.312 pandas-1.5.3

In [2]:
import os, getpass
from pandas import read_csv

In [ ]:
credentials = {
    "url" : "https://jp-tok.ml.cloud.ibm.com" ,
    "apikey" : getpass.getpass("Enter your API key")
}

Enter your API key ········

In [22]:
try:
    project_id = os.environ["PROJECT_ID"]
except KeyError:
    project_id = input("Enter your Project ID")

In [23]:
project_id

'662f4904-0344-4ea9-b975-da4745bbb2a1'

In [ ]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='<YOUR_IBM_API_KEY>',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud')

bucket = 'kavyassandbox-donotdelete-pr-wsdtmnplnybaxh'
object_key = 'car_rental_train.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_1 = pd.read_csv(body)
df_1.head(10)

In [ ]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='<YOUR_IBM_API_KEY>',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud')

bucket = 'kavyassandbox-donotdelete-pr-wsdtmnplnybaxh'
object_key = 'car_rental_test.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_2 = pd.read_csv(body)
df_2.head(10)

In [ ]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='<YOUR_IBM_API_KEY>',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud')

bucket = 'kavyassandbox-donotdelete-pr-wsdtmnplnybaxh'
object_key = 'car_rental_train.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_data = pd.read_csv(body)
train_data.head(5)

,ID,Gender,Age,Customer Status,Customer Service,Satisfaction,Business Area
0,1,Male,23,Active,The app crashed multiple times,0,App Usability
1,2,Other,67,Active,Pricing was transparent and fair,0,Pricing
2,3,Male,60,Inactive,I had to wait too long for dropoff,0,Dropoff Process
3,4,Female,31,Active,Dropoff was fast and efficient,0,Dropoff Process
4,5,Female,50,Active,Had trouble locating the rental office,1,Pickup Process

In [ ]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='<YOUR_IBM_API_KEY>',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud')

bucket = 'kavyassandbox-donotdelete-pr-wsdtmnplnybaxh'
object_key = 'car_rental_test.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_data = pd.read_csv(body)
test_data.head(5)

,ID,Gender,Age,Customer Status,Customer Service,Satisfaction,Business Area
0,1,Female,68,Active,Staff at pickup were helpful,0,Pickup Process
1,2,Male,40,Inactive,I received an old model with scratches,0,Vehicle Quality
2,3,Male,33,Inactive,Confusing dropoff instructions,0,Dropoff Process
3,4,Male,44,Active,Dropoff was fast and efficient,1,Dropoff Process
4,5,Male,61,Inactive,Difficult to navigate the app,1,App Usability

In [26]:
train_data.shape

(500, 7)

In [27]:
test_data.shape

(10, 7)

In [28]:
from ibm_watson_machine_learning.foundation_models.utils.enums import ModelTypes

In [29]:
model_id = ModelTypes.FLAN_UL2

In [30]:
satisfaction_instruction = """
Was customer satisfied?\n

comment: I have had a few recent rentals that have taken a very long time , 
with no offer of apology.
In the most recent case , the agent subsequently offered me a car type on
an upgrade coupon and then told me it was no longer available\n

satisfaction :0\n\n
"""

In [31]:
from ibm_watson_machine_learning.metanames import GenTextParamsMetaNames as GenParams

parameters = {
    GenParams.MAX_NEW_TOKENS: 10
}

In [32]:
from ibm_watson_machine_learning.foundation_models import Model

model = Model(
    model_id = model_id,
    params = parameters,
    credentials = credentials,
    project_id=project_id)

In [61]:
results = []
comments = list(test_data["Customer Service"])
satisfaction = test_data["Satisfaction"].astype(str).tolist()

for input_text in comments:
    results.append(model.generate_text(prompt=" ".join([satisfaction_instruction,input_text])))

In [62]:
comments

['Staff at pickup were helpful',
 'I received an old model with scratches',
 'Confusing dropoff instructions',
 'Dropoff was fast and efficient',
 'Difficult to navigate the app',
 'The vehicle had mechanical issues',
 'Customer support was very helpful',
 'No one responded to my issue',
 'The rental price was too high',
 'Dropoff was fast and efficient']

In [63]:
satisfaction

['0', '0', '0', '1', '1', '0', '0', '0', '1', '1']

In [64]:
results

['no', 'no', 'no', 'no', 'no', 'no', 'satisfaction :1', 'No', 'no', 'no']

In [50]:
business_area_instruction = """
Find the business area of the customer email.
Choose business area from the following list:
'App Usability' , 'Pricing' , 'Dropoff Process' , 
'Pickup Process' , 'Customer Support' , 'Vehicle Quality ' \n

comment : I do not understand why I have to pay additional fee if vehicle is 
returned without a full tank. \n
business area : 'Pricing' \n\n

"""

In [51]:
from ibm_watson_machine_learning.metanames import GenTextParamsMetaNames as GenParams

parameters = {
    GenParams.MAX_NEW_TOKENS: 15
}

In [53]:
from ibm_watson_machine_learning.foundation_models import Model

model = Model(
    model_id = model_id,
    params = parameters,
    credentials = credentials,
    project_id=project_id)

In [65]:
results = []
comments = list(test_data["Customer Service"])
area = list(test_data["Business Area"])

for input_text in comments:
    results.append(model.generate_text(prompt=" ".join([business_area_instruction,input_text])))

In [66]:
comments

['Staff at pickup were helpful',
 'I received an old model with scratches',
 'Confusing dropoff instructions',
 'Dropoff was fast and efficient',
 'Difficult to navigate the app',
 'The vehicle had mechanical issues',
 'Customer support was very helpful',
 'No one responded to my issue',
 'The rental price was too high',
 'Dropoff was fast and efficient']

In [67]:
area

['Pickup Process',
 'Vehicle Quality',
 'Dropoff Process',
 'Dropoff Process',
 'App Usability',
 'Vehicle Quality',
 'Customer Support',
 'Customer Support',
 'Pricing',
 'Dropoff Process']

In [68]:
results

['Pickup Process',
 'Vehicle Quality',
 'Dropoff Process',
 'Dropoff Process',
 'App Usability',
 'Vehicle Quality',
 'Customer Support',
 'Customer Support',
 'Pricing',
 'Dropoff Process']